server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:sqlite.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: true
